-- MySQL Script generated by MySQL Workbench
-- Tue Mar 24 15:43:48 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema diy_searcher
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema diy_searcher
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `diy_searcher` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `diy_searcher` ;

-- -----------------------------------------------------
-- Table `diy_searcher`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diy_searcher`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diy_searcher`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diy_searcher`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  `ratings` INT NULL,
  `expensive` INT NULL,
  `difficulty` INT NULL,
  `image` VARCHAR(255) NULL,
  `video` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `user_id` INT NOT NULL,
  `kit_id` INT NOT NULL,
  `step_id` INT NOT NULL,
  `comment_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diy_searcher`.`steps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diy_searcher`.`steps` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  `description` LONGTEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diy_searcher`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diy_searcher`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `comment` LONGTEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diy_searcher`.`kits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diy_searcher`.`kits` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `prices` FLOAT NULL,
  `description` LONGTEXT NULL,
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diy_searcher`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diy_searcher`.`orders` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `address_id` INT NULL,
  `cart_id` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diy_searcher`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diy_searcher`.`addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(255) NULL,
  `city` VARCHAR(45) NULL,
  `zip_code` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diy_searcher`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diy_searcher`.`cart` (
  `order_id` INT NOT NULL,
  `kit_id` INT NOT NULL,
  `quantity` INT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diy_searcher`.`projects_have_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diy_searcher`.`projects_have_tags` (
  `project_id` INT NOT NULL,
  `tag_id` VARCHAR(45) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diy_searcher`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diy_searcher`.`tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
